# WATCH OUT WITH EDITING!!! READ THE DESCRIPTIONS BEFORE DOING SOMETHING

# If the moderation action should be send globally ([user] has been banned for "reason")
# or If it should be send to only mods!
# log-type can be: global, staff or none
log-type: global

